export default {
  farm_activity: {
    label: 'Activity',
    label_plural: 'Activities',
    fields: {
      area: {
        label: 'Areas',
        type: 'taxonomy_term_reference',
        required: 0,
        default_value: [],
      },
      asset: {
        label: 'Assets',
        type: 'entityreference',
        required: 0,
        default_value: [],
      },
      files: {
        label: 'Files',
        type: 'file',
        required: 0,
        default_value: [],
      },
      geofield: {
        label: 'Geometry',
        type: 'geofield',
        required: 0,
        default_value: null,
      },
      images: {
        label: 'Photos',
        type: 'image',
        required: 0,
        default_value: [],
      },
      notes: {
        label: 'Notes',
        type: 'text_long',
        required: 0,
        default_value: null,
      },
      movement: {
        label: 'Movement',
        type: 'field_collection',
        required: 0,
        default_value: null,
      },
      log_category: {
        label: 'Log category',
        type: 'taxonomy_term_reference',
        required: 0,
        default_value: null,
      },
      log_owner: {
        label: 'Assigned to',
        type: 'entityreference',
        required: 0,
        default_value: null,
      },
      inventory: {
        label: 'Inventory adjustments',
        type: 'field_collection',
        required: 0,
        default_value: null,
      },
      membership: {
        label: 'Group membership',
        type: 'field_collection',
        required: 0,
        default_value: null,
      },
      quantity: {
        label: 'Quantity',
        type: 'field_collection',
        required: 0,
        default_value: null,
      },
      flags: {
        label: 'Flags',
        type: 'list_text',
        required: 0,
        default_value: null,
      },
      data: {
        label: 'Data',
        type: 'text_long',
        required: 0,
        default_value: null,
      },
      equipment: {
        label: 'Equipment used',
        type: 'entityreference',
        required: 0,
        default_value: null,
      },
    },
  },
  farm_harvest: {
    label: 'Harvest',
    label_plural: 'Harvests',
    fields: {
      files: {
        label: 'Files',
        type: 'file',
        required: 0,
        default_value: [],
      },
      geofield: {
        label: 'Geometry',
        type: 'geofield',
        required: 0,
        default_value: null,
      },
      images: {
        label: 'Photos',
        type: 'image',
        required: 0,
        default_value: [],
      },
      notes: {
        label: 'Notes',
        type: 'text_long',
        required: 0,
        default_value: null,
      },
      quantity: {
        label: 'Quantity',
        type: 'field_collection',
        required: 0,
        default_value: null,
      },
      asset: {
        label: 'Assets',
        type: 'entityreference',
        required: 0,
        default_value: null,
      },
      movement: {
        label: 'Movement',
        type: 'field_collection',
        required: 0,
        default_value: null,
      },
      area: {
        label: 'Areas',
        type: 'taxonomy_term_reference',
        required: 0,
        default_value: null,
      },
      log_category: {
        label: 'Log category',
        type: 'taxonomy_term_reference',
        required: 0,
        default_value: null,
      },
      log_owner: {
        label: 'Assigned to',
        type: 'entityreference',
        required: 0,
        default_value: null,
      },
      lot_number: {
        label: 'Harvest lot number',
        type: 'text',
        required: 0,
        default_value: null,
      },
      inventory: {
        label: 'Inventory adjustments',
        type: 'field_collection',
        required: 0,
        default_value: null,
      },
      flags: {
        label: 'Flags',
        type: 'list_text',
        required: 0,
        default_value: null,
      },
      data: {
        label: 'Data',
        type: 'text_long',
        required: 0,
        default_value: null,
      },
      equipment: {
        label: 'Equipment used',
        type: 'entityreference',
        required: 0,
        default_value: null,
      },
    },
  },
  farm_input: {
    label: 'Input',
    label_plural: 'Inputs',
    fields: {
      area: {
        label: 'Areas',
        type: 'taxonomy_term_reference',
        required: 0,
        default_value: [],
      },
      files: {
        label: 'Files',
        type: 'file',
        required: 0,
        default_value: [],
      },
      geofield: {
        label: 'Geometry',
        type: 'geofield',
        required: 0,
        default_value: null,
      },
      images: {
        label: 'Photos',
        type: 'image',
        required: 0,
        default_value: [],
      },
      input_method: {
        label: 'Application method',
        type: 'text',
        required: 0,
        default_value: null,
      },
      input_purpose: {
        label: 'Purpose',
        type: 'text',
        required: 0,
        default_value: null,
      },
      input_source: {
        label: 'Source/manufacturer',
        type: 'text',
        required: 0,
        default_value: null,
      },
      material: {
        label: 'Materials',
        type: 'taxonomy_term_reference',
        required: 0,
        default_value: null,
      },
      notes: {
        label: 'Notes',
        type: 'text_long',
        required: 0,
        default_value: null,
      },
      quantity: {
        label: 'Quantity',
        type: 'field_collection',
        required: 0,
        default_value: null,
      },
      asset: {
        label: 'Assets',
        type: 'entityreference',
        required: 0,
        default_value: null,
      },
      movement: {
        label: 'Movement',
        type: 'field_collection',
        required: 0,
        default_value: null,
      },
      log_category: {
        label: 'Log category',
        type: 'taxonomy_term_reference',
        required: 0,
        default_value: null,
      },
      log_owner: {
        label: 'Assigned to',
        type: 'entityreference',
        required: 0,
        default_value: null,
      },
      lot_number: {
        label: 'Input lot number',
        type: 'text',
        required: 0,
        default_value: null,
      },
      date_purchase: {
        label: 'Date purchased',
        type: 'datestamp',
        required: 0,
        default_value: null,
      },
      inventory: {
        label: 'Inventory adjustments',
        type: 'field_collection',
        required: 0,
        default_value: null,
      },
      flags: {
        label: 'Flags',
        type: 'list_text',
        required: 0,
        default_value: null,
      },
      data: {
        label: 'Data',
        type: 'text_long',
        required: 0,
        default_value: null,
      },
      equipment: {
        label: 'Equipment used',
        type: 'entityreference',
        required: 0,
        default_value: null,
      },
    },
  },
  farm_observation: {
    label: 'Observation',
    label_plural: 'Observations',
    fields: {
      area: {
        label: 'Areas',
        type: 'taxonomy_term_reference',
        required: 0,
        default_value: [],
      },
      asset: {
        label: 'Assets',
        type: 'entityreference',
        required: 0,
        default_value: [],
      },
      files: {
        label: 'Files',
        type: 'file',
        required: 0,
        default_value: [],
      },
      geofield: {
        label: 'Geometry',
        type: 'geofield',
        required: 0,
        default_value: null,
      },
      images: {
        label: 'Photos',
        type: 'image',
        required: 0,
        default_value: [],
      },
      notes: {
        label: 'Notes',
        type: 'text_long',
        required: 0,
        default_value: null,
      },
      quantity: {
        label: 'Quantity',
        type: 'field_collection',
        required: 0,
        default_value: null,
      },
      movement: {
        label: 'Movement',
        type: 'field_collection',
        required: 0,
        default_value: null,
      },
      log_category: {
        label: 'Log category',
        type: 'taxonomy_term_reference',
        required: 0,
        default_value: null,
      },
      log_owner: {
        label: 'Assigned to',
        type: 'entityreference',
        required: 0,
        default_value: null,
      },
      membership: {
        label: 'Group membership',
        type: 'field_collection',
        required: 0,
        default_value: null,
      },
      inventory: {
        label: 'Inventory adjustments',
        type: 'field_collection',
        required: 0,
        default_value: null,
      },
      flags: {
        label: 'Flags',
        type: 'list_text',
        required: 0,
        default_value: null,
      },
      data: {
        label: 'Data',
        type: 'text_long',
        required: 0,
        default_value: null,
      },
      equipment: {
        label: 'Equipment used',
        type: 'entityreference',
        required: 0,
        default_value: null,
      },
    },
  },
};
